### ISSUE TITLE
Add-on is not compatible with Vaadin 24.3

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/fc-applayout#22]
When compiling with 24.3.0.rc1 I get the following error

```
[ERROR] [31mExpression expected (Note that you need plugins to import files that are not JavaScript)[39m
[ERROR] file: [36m/var/jenkins/workspace/AddonsDemo-v24/node_modules/@flowingcode/fc-applayout/src/fc-applayout.ts:36:0[39m
[ERROR] [33m34:  * @csspart button - The button
[ERROR] 35:  */
[ERROR] 36: @customElement('fc-applayout')
[ERROR] ^
[ERROR] 37: export class FcAppLayoutElement extends ThemableMixin(LitElement) {
[ERROR] 38:   static get is() { return 'fc-applayout'; }[39m
[ERROR] [31merror during build:
[ERROR] RollupError: Expression expected
[ERROR] at error (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
[ERROR] at nodeConverters (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:2084:9)
[ERROR] at convertNode (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
[ERROR] at convertProgram (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:960:48)
[ERROR] at parseAstAsync (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:2150:20)
[ERROR] at async Module.tryParseAsync (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13496:21)
[ERROR] at async Module.setSource (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13077:35)
[ERROR] at async ModuleLoader.addModuleSource (file:///var/jenkins/workspace/AddonsDemo-v24/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17724:13)[39m
```

**Comment by javier-godoy** [comment]
This may be related to Vaadin 24.3 upgrading to Lit 3.

**Comment by mlopezFC** [comment]
This was fixed in [this PR](https://github.com/FlowingCode/fc-applayout/pull/23)
